# Generated by Django 6.0.7 on 2026-07-16 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('challenge_invitation', 'Challenge Invitation'), ('submission_reviewed', 'Submission Reviewed'), ('shortlisted', 'Shortlisted'), ('new_submission', 'New Submission')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_id', models.UUIDField(blank=True, help_text='The unique UUID string identifier of the originating object (Invite, Submission, etc.).', null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
