# Generated by Django 6.0.7 on 2026-07-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='job_link',
            field=models.URLField(blank=True, help_text='URL for job offer notifications.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('challenge_invitation', 'Challenge Invitation'), ('submission_reviewed', 'Submission Reviewed'), ('shortlisted', 'Shortlisted'), ('new_submission', 'New Submission'), ('job_offer', 'Job Offer')], max_length=50),
        ),
    ]
