# Generated by Django 6.0.7 on 2026-07-16 13:52

import django.core.validators
import django.db.models.deletion
import submissions.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='submissions/reports/', validators=[submissions.validators.validate_document])),
                ('slides_file', models.FileField(blank=True, null=True, upload_to='submissions/slides/', validators=[submissions.validators.validate_document])),
                ('spreadsheet_file', models.FileField(blank=True, null=True, upload_to='submissions/spreadsheets/', validators=[submissions.validators.validate_document])),
                ('other_file', models.FileField(blank=True, null=True, upload_to='submissions/other/', validators=[submissions.validators.validate_document])),
                ('report_link', models.URLField(blank=True)),
                ('design_link', models.URLField(blank=True)),
                ('github_repository', models.URLField(blank=True)),
                ('slides_link', models.URLField(blank=True)),
                ('video_link', models.URLField(blank=True)),
                ('spreadsheet_link', models.URLField(blank=True)),
                ('company_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('feedback', models.TextField(blank=True)),
                ('shortlisted', models.BooleanField(default=False)),
                ('cash_prize_awarded', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed')], default='submitted', max_length=20)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.challenge')),
                ('intern', models.ForeignKey(help_text='The individual talent or team representative submitting the files.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Leave blank if this is a solo submission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='challenges.challengeteam')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('challenge', 'intern'), ('challenge', 'team')},
            },
        ),
    ]
