from django.urls import path
from .views import (
    AcceptChallengeInviteView,
    ChallengeCreateView,
    ChallengeDeleteView,
    ChallengeDetailView,
    ChallengeListView,
    ChallengeUpdateView,
    CreateChallengeInviteView,
    CreateChallengeTeamView,
    DeclineChallengeInviteView,
    MyChallengesView,
    MyTeamsView,
    ReceivedInvitesView,
)

urlpatterns = [
    path(
        "",
        ChallengeListView.as_view(),
        name="challenge-list",
    ),
    path(
        "my/",
        MyChallengesView.as_view(),
        name="my-challenges",
    ),
    path(
        "create/",
        ChallengeCreateView.as_view(),
        name="challenge-create",
    ),
    path(
        "<uuid:pk>/",
        ChallengeDetailView.as_view(),
        name="challenge-detail",
    ),
    path(
        "<uuid:pk>/update/",
        ChallengeUpdateView.as_view(),
        name="challenge-update",
    ),
    path(
        "<uuid:pk>/delete/",
        ChallengeDeleteView.as_view(),
        name="challenge-delete",
    ),
    path(
        "teams/",
        CreateChallengeTeamView.as_view(),
        name="create-team",
    ),
    path(
        "teams/my/",
        MyTeamsView.as_view(),
        name="my-teams",
    ),
    path(
        "invites/",
        CreateChallengeInviteView.as_view(),
        name="create-invite",
    ),
    path(
        "invites/received/",
        ReceivedInvitesView.as_view(),
        name="received-invites",
    ),
    
    path(
        "invites/<uuid:pk>/accept/",
        AcceptChallengeInviteView.as_view(),
        name="accept-invite",
    ),
    path(
        "invites/<int:pk>/decline/",
        DeclineChallengeInviteView.as_view(),
        name="decline-invite",
    ),
]
